Update appearance-menu
All messages transferred to one block. Status messages disclosed.

diff --git a/bin/appearance-menu b/bin/appearance-menu
--- a/bin/appearance-menu
+++ b/bin/appearance-menu
@@ -5,6 +5,35 @@ BLUE='\e[44m'
 ORANGE='\e[46m'
 NC='\e[0m'
 
+STATUSVAR=0
+CANCELSTATUS=0
+SELECTEDITEM=""
+TEXTEDITOR=$EDITOR
+
+# Service messages section
+CONTINMSG="$BLUE Press any key to continue$NC"
+ERRORMSG="$RED Wrong.$NC"
+TRYAGAINMSG="$RED Press any key and try again$NC"
+AVAILABLETHEMESMSG="Available themes:"
+PS31MSG="Choose new gtk2 theme:"
+PS32MSG="Choose new gtk3 theme:"
+PS33MSG="Choose new icon theme:"
+PS34MSG="Choose new pointer theme:"
+SETTINGGTK2THEMEMSG='Setting theme to %s'
+SETTINGGTK3THEMEMSG='Setting theme to %s'
+SETTINGICONTHEMEMSG='Setting theme to %s'
+SETTINGPOINTERTHMSG='Setting theme to %s'
+GTK2THEMEPREFIXMSG="GTK2 theme "
+GTK3THEMEPREFIXMSG="GTK3 theme "
+ICONTHEMEPREFIXMSG="Icon theme "
+POINTERTHPREFIXMSG="Pointer theme "
+FONTSETPREFIXMSG="Font "
+FONTSIZESETMSG=" with size "
+INPUTFONTSIZEMSG="Input the size of the font:"
+CHOOSEFONTPROMPTMSG="Choose new font to use"
+SETSUFFIXMSG=" was set successfully"
+TOGGLEDARKTHEMEMSG="Done"
+
 if ! [ -f "$HOME/.gtkrc-2.0" ]; then
 	cat > $HOME/.gtkrc-2.0 <<EOL
 include "$HOME/.gtkrc-2.0.mine"
@@ -63,101 +92,119 @@ fi
 function set_gtk2_theme {
 	new_theme="$@"
 	cp $HOME/.gtkrc-2.0 $HOME/.gtkrc-2.0.bak && sed -i "s/$(grep "gtk-theme-name" .gtkrc-2.0)/gtk-theme-name=\"$new_theme\"/g" .gtkrc-2.0
+	STATUSVAR=$?
 }
 
 function choose_gtk2_theme {
-PS3="Choose new gtk2 theme: "
-# Gather the results in an array.
-gtk2_themes=($(find /usr/share/themes -type d -name "gtk-2.0" | awk -F'/' '{print $5}') "proceed" "cancel")
+	echo $AVAILABLETHEMESMSG
+	PS3=$PS31MSG
+	CANCELSTATUS=0
+	# Gather the results in an array.
+	gtk2_themes=($(find /usr/share/themes -type d -name "gtk-2.0" | awk -F'/' '{print $5}') "cancel")
 
-select pick in "${gtk2_themes[@]}"
-do
-	case $pick in
-		proceed)
-			break
-			;;
-		cancel)
-			exit
-			;;		
-		*)	
-			picks+=("$pick")
-			break
-			;;		
-	esac
-done
+	select pick in "${gtk2_themes[@]}"
+	do
+		case $pick in
+			cancel)
+				CANCELSTATUS=1
+				break
+				;;		
+			*)	
+				picks+=("$pick")
+				break
+				;;		
+		esac
+	done
 
-if [[ $picks ]]; then
-    printf 'Setting theme to %s\n' "${picks[*]}"
-    set_gtk2_theme "${picks[@]}"
-    picks=()
-fi
+	if [ $CANCELSTATUS -eq 1 ]; then
+		echo ""
+	else 
+		if [[ $picks ]]; then
+    		printf "$SETTINGGTK2THEMEMSG" "${picks[*]}"
+   			SELECTEDITEM="${picks[@]}"
+    		set_gtk2_theme $SELECTEDITEM
+    		picks=()
+   	 	fi
+	fi
 }
 
 function set_gtk3_theme {
 	new_theme="$@"
 	cp $HOME/.config/gtk-3.0/settings.ini $HOME/.config/gtk-3.0/settings.ini.bak && sed -i "s/$(grep "gtk-theme-name" $HOME/.config/gtk-3.0/settings.ini)/gtk-theme-name=$new_theme/g" $HOME/.config/gtk-3.0/settings.ini
+	STATUSVAR=$?
 }
 
 function choose_gtk3_theme {
-PS3="Choose new gtk3 theme: "
-# Gather the results in an array.
-gtk3_themes=($(find /usr/share/themes -type d -name "gtk-3.0" | awk -F'/' '{print $5}') "proceed" "cancel")
+	echo $AVAILABLETHEMESMSG
+	PS3=$PS32MSG
+	CANCELSTATUS=0
+	# Gather the results in an array.
+	gtk3_themes=($(find /usr/share/themes -type d -name "gtk-3.0" | awk -F'/' '{print $5}') "cancel")
 
-select pick in "${gtk3_themes[@]}"
-do
-	case $pick in
-		proceed)
-			break
-			;;
-		cancel)
-			exit
-			;;		
-		*)	
-			picks+=("$pick")
-			break
-			;;		
-	esac
-done
+	select pick in "${gtk3_themes[@]}"
+	do
+		case $pick in
+			cancel)
+				CANCELSTATUS=1
+				break
+				;;		
+			*)	
+				picks+=("$pick")
+				break
+				;;		
+		esac
+	done
 
-if [[ $picks ]]; then
-    printf 'Setting theme to %s\n' "${picks[*]}"
-    set_gtk3_theme "${picks[@]}"
-    picks=()
-fi
+	if [ $CANCELSTATUS -eq 1 ]; then
+		echo ""
+	else 
+		if [[ $picks ]]; then
+    		printf "$SETTINGGTK3THEMEMSG" "${picks[*]}"
+    		SELECTEDITEM="${picks[@]}"
+    		set_gtk3_theme $SELECTEDITEM
+    		picks=()
+    	fi
+	fi
 }
 
 function set_icon_theme {
 	new_theme="$@"
 	cp $HOME/.config/gtk-3.0/settings.ini $HOME/.config/gtk-3.0/settings.ini.bak && sed -i "s/$(grep "gtk-icon-theme-name" $HOME/.config/gtk-3.0/settings.ini)/gtk-icon-theme-name=$new_theme/g" $HOME/.config/gtk-3.0/settings.ini
 	cp $HOME/.gtkrc-2.0 $HOME/.gtkrc-2.0.bak && sed -i "s/$(grep "gtk-icon-theme-name" $HOME/.gtkrc-2.0)/gtk-icon-theme-name=\"$new_theme\"/g" $HOME/.gtkrc-2.0	
+	STATUSVAR=$?
 }
 
 function choose_icon_theme {
-PS3="Choose new icon theme: "
-# Gather the results in an array.
-icon_themes=($(find /usr/share/icons -type f -name "index.theme" | awk -F'/' '{print $5}') "proceed" "cancel")
+	echo $AVAILABLETHEMESMSG
+	PS3=$PS33MSG
+	CANCELSTATUS=0
+	# Gather the results in an array.
+	icon_themes=($(find /usr/share/icons -type f -name "index.theme" | awk -F'/' '{print $5}') "cancel")
 
-select pick in "${icon_themes[@]}"
-do
-	case $pick in
-		proceed)
-			break
-			;;
-		cancel)
-			exit
-			;;		
-		*)	
-			picks+=("$pick")
-			break
-			;;		
-	esac
-done
+	select pick in "${icon_themes[@]}"
+	do
+		case $pick in
+			cancel)
+				CANCELSTATUS=1
+				break
+				;;		
+			*)	
+				picks+=("$pick")
+				break
+				;;		
+		esac
+	done
 
-if [[ $picks ]]; then
-    printf 'Setting theme to %s\n' "${picks[*]}"
-    set_icon_theme "${picks[@]}"
-    picks=()
-fi
+	if [ $CANCELSTATUS -eq 1 ]; then
+		echo ""
+	else
+		if [[ $picks ]]; then
+    		printf "$SETTINGICONTHEMEMSG" "${picks[*]}"
+    		SELECTEDITEM="${picks[@]}"
+    		set_icon_theme $SELECTEDITEM
+    		picks=()
+    	fi
+	fi
 }
 
 function set_pointer_theme {
@@ -165,55 +212,76 @@ function set_pointer_theme {
 	cp $HOME/.icons/default/index.theme $HOME/.icons/default/index.theme.bak && sed -i "s/$(grep "Inherits" $HOME/.icons/default/index.theme)/Inherits=$new_theme/g" $HOME/.icons/default/index.theme
 	cp $HOME/.config/gtk-3.0/settings.ini $HOME/.config/gtk-3.0/settings.ini.bak && sed -i "s/$(grep "gtk-cursor-theme-name" $HOME/.config/gtk-3.0/settings.ini)/gtk-cursor-theme-name=$new_theme/g" $HOME/.config/gtk-3.0/settings.ini
 	cp $HOME/.gtkrc-2.0 $HOME/.gtkrc-2.0.bak && sed -i "s/$(grep "gtk-cursor-theme-name" $HOME/.gtkrc-2.0)/gtk-cursor-theme-name=\"$new_theme\"/g" $HOME/.gtkrc-2.0
+	STATUSVAR=$?
 }
 
 function choose_pointer_theme {
-PS3="Choose new pointer theme: "
-# Gather the results in an array.
-pointer_themes=($(find /usr/share/icons -type d -name "cursors" | awk -F'/' '{print $5}' | sed 's/-Cursor//g') "proceed" "cancel")
+	echo $AVAILABLETHEMESMSG
+	PS3=$PS34MSG
+	CANCELSTATUS=0
+	# Gather the results in an array.
+	pointer_themes=($(find /usr/share/icons -type d -name "cursors" | awk -F'/' '{print $5}' | sed 's/-Cursor//g') "cancel")
 
-select pick in "${pointer_themes[@]}"
-do
-	case $pick in
-		proceed)
-			break
-			;;
-		cancel)
-			exit
-			;;		
-		*)	
-			picks+=("$pick")
-			break
-			;;		
-	esac
-done
+	select pick in "${pointer_themes[@]}"
+	do
+		case $pick in
+			cancel)
+				CANCELSTATUS=1
+				break
+				;;		
+			*)	
+				picks+=("$pick")
+				break
+				;;		
+		esac
+	done
 
-if [[ $picks ]]; then
-    printf 'Setting theme to %s\n' "${picks[*]}"
-    set_pointer_theme "${picks[@]}"
-    picks=()
-fi
+	if [ $CANCELSTATUS -eq 1 ]; then
+		echo ""
+	else
+		if [[ $picks ]]; then
+    		printf "$SETTINGPOINTERTHMSG" "${picks[*]}"
+    		SELECTEDITEM="${picks[@]}"
+    		set_pointer_theme $SELECTEDITEM
+    		picks=()
+    	fi
+	fi
 }
 
 function set_font {
 	new_theme="$@"
 	cp $HOME/.config/gtk-3.0/settings.ini $HOME/.config/gtk-3.0/settings.ini.bak && sed -i "s/$(grep "gtk-font-name" $HOME/.config/gtk-3.0/settings.ini)/gtk-font-name=$new_theme/g" $HOME/.config/gtk-3.0/settings.ini
 	cp $HOME/.gtkrc-2.0 $HOME/.gtkrc-2.0.bak && sed -i "s/$(grep "gtk-font-name" $HOME/.gtkrc-2.0)/gtk-font-name=\"$new_theme\"/g" $HOME/.gtkrc-2.0	
+	STATUSVAR=$?
 }
 
 function choose_font {
-new_font=$(fc-list : family | tr , \\n | fzf -e --reverse --prompt="< Choose new font to use >")
-echo "  Input the size of the font"
-read font_size
-
-set_font $new_font $font_size
+	font_size=0
+	SELECTEDITEM=$(fc-list : family | tr , \\n | fzf -e --reverse --prompt="< $CHOOSEFONTPROMPTMSG >")
+	if [ $SELECTEDITEM != "" ]; then
+		new_font=$SELECTEDITEM
+    	echo $INPUTFONTSIZEMSG
+    	read font_size
+    	if [ $font_size -gt 0 ]; then
+    		set_font $new_font $font_size
+    	else
+    		STATUSVAR=1
+    	fi
+	else
+		STATUSVAR=1
+	fi
 }
 
 function toggle_dark_theme {
 	grep -q "gtk-application-prefer-dark-theme=" $HOME/.config/gtk-3.0/settings.ini || echo "gtk-application-prefer-dark-theme=1" >> $HOME/.config/gtk-3.0/settings.ini
+	
+	STATUSVAR=$?
+	
 	grep -q "gtk-application-prefer-dark-theme=1" $HOME/.config/gtk-3.0/settings.ini && \
 	sed -i "s/gtk-application-prefer-dark-theme=1/gtk-application-prefer-dark-theme=0/g" $HOME/.config/gtk-3.0/settings.ini || \
 	sed -i "s/gtk-application-prefer-dark-theme=0/gtk-application-prefer-dark-theme=1/g" $HOME/.config/gtk-3.0/settings.ini
+	
+	STATUSVAR+=$?
 }
 
 function main {
@@ -234,58 +302,108 @@ function main {
     case $choix in
         1)
             echo
+            STATUSVAR=1
+            SELECTEDITEM=""
             choose_gtk2_theme
-            echo ""
+            if [ $STATUSVAR -eq 0 ]; then
+            	echo ""
+            	echo -e "$GTK2THEMEPREFIXMSG$SELECTEDITEM$SETSUFFIXMSG"
+            	echo -e "$CONTINMSG"
+            	read -s -n1
+            else
+            	echo ""
+            fi            	
             ;;
         2)
             echo
+            STATUSVAR=1
+            SELECTEDITEM=""
             choose_gtk3_theme
-            echo ""
+            if [ $STATUSVAR -eq 0 ]; then
+            	echo ""
+            	echo -e "$GTK3THEMEPREFIXMSG$SELECTEDITEM$SETSUFFIXMSG"
+            	echo -e "$CONTINMSG"
+            	read -s -n1
+            else
+            	echo ""
+            fi
             ;;
         3)
             echo
+            STATUSVAR=1
+            SELECTEDITEM=""
             choose_font
-            echo ""
+            if [ $STATUSVAR -eq 0 ]; then
+            	echo ""
+            	echo -e "$FONTSETPREFIXMSG$SELECTEDITEM$FONTSIZESETMSG$font_size$SETSUFFIXMSG"
+            	echo -e "$CONTINMSG"
+            	read -s -n1
+            else
+            	echo ""
+            fi
             ;;
         4)
             echo
+            STATUSVAR=1
+            SELECTEDITEM=""
             choose_icon_theme
-            echo ""
+            if [ $STATUSVAR -eq 0 ]; then
+            	echo ""
+            	echo -e "$ICONTHEMEPREFIXMSG$SELECTEDITEM$SETSUFFIXMSG"
+            	echo -e "$CONTINMSG"
+            	read -s -n1
+            else
+            	echo ""
+            fi
             ;;
         5)
             echo
+            STATUSVAR=1
             toggle_dark_theme
-            echo ""
+            if [ $STATUSVAR -eq 0 ]; then
+            	echo ""
+            	echo -e "$TOGGLEDARKTHEMEMSG"
+            	echo -e "$CONTINMSG"
+            	read -s -n1
+            else
+            	echo ""
+            fi
             ;;
         6)
             echo
+            STATUSVAR=1
+            SELECTEDITEM=""
             choose_pointer_theme
-            echo ""
+            if [ $STATUSVAR -eq 0 ]; then
+            	echo ""
+            	echo -e "$POINTERTHPREFIXMSG$SELECTEDITEM$SETSUFFIXMSG"
+            	echo -e "$CONTINMSG"
+            	read -s -n1
+            else
+            	echo ""
+            fi
             ;;
         7)
             echo
-            nano $HOME/.gtkrc-2.0
+            $TEXTEDITOR $HOME/.gtkrc-2.0
             echo ""
             ;;
         8)
             echo
-            nano $HOME/.config/gtk-3.0/settings.ini
+            $TEXTEDITOR $HOME/.config/gtk-3.0/settings.ini
             echo ""
             ;;
         9)
             echo
-            nano $HOME/.Xresources
+            $TEXTEDITOR $HOME/.Xresources
             echo ""
             ;;
         0)
             clear && exit
-            read
             ;;
         *)
-            echo -e "$RED Unknown option $NC"
-            echo "Wait and try again later..."
-            echo ""
-            sleep 3
+			echo -e "$ERRORMSG$TRYAGAINMSG"
+            read -s -n1
             clear
             ;;
     esac
