Update initmenu-openrc
There were bugs with sudo, when I pressed ESC it asked me about password.

diff --git a/bin/initmenu-openrc b/bin/initmenu-openrc
--- a/bin/initmenu-openrc
+++ b/bin/initmenu-openrc
@@ -4,50 +4,132 @@ RED='\e[41m'
 BLUE='\e[44m'
 ORANGE='\e[46m'
 NC='\e[0m'
+STATUSVAR=0
+TEXTEDITOR=$EDITOR
+
+# Service messages section
+CONTINMSG="Press any key to continue"
+ERRORMSG="$RED Wrong option $NC"
+TRYAGAINMSG="Press Enter and try again"
+SELECTFILEMSG="Select file to configure and press Enter: "
+SELECTTARGETMSG="Select target and press Enter to change to: "
+SERVICESTARTEDMSG="Service was started successfully"
+SERVICEENABLEDMSG="Service was enabled successfully"
+SERVICESTOPPEDMSG="Service was stopped successfully"
+SERVICEDISABLEDMSG="Service was disabled successfully"
 
 function config_editor {
-PS3="Select file to configure: "
-configs=("xdm" "rc.local" "sysctl.conf" "modules" "cancel")
+PS3="$SELECTFILEMSG"
+configs=("journald.conf" "system.conf" "logind.conf" "user.conf" "cancel")
 
 select pick in "${configs[@]}"
 do
 	case $pick in
-		xdm)
-			sudo nano /etc/conf.d/xdm
+		logind.conf)
+			sudo $TEXTEDITOR /etc/systemd/logind.conf 
 			break
 			;;		
-		rc.local)
-			sudo nano /etc/rc.local
+		system.conf)
+			sudo $TEXTEDITOR /etc/systemd/system.conf
 			break
 			;;		
-		sysctl.conf)
-			sudo nano /etc/sysctl.conf
+		journald.conf)
+			sudo $TEXTEDITOR /etc/systemd/journald.conf
 			break
 			;;		
-		modules)
-			sudo nano /etc/conf.d/modules
+		user.conf)
+			sudo $TEXTEDITOR /etc/systemd/user.conf
 			break
 			;;		
 		cancel)
 			break
 	esac
-done	
-} 
+done
+	
+}
+
+function change_runlevel {
+PS3="$SELECTTARGETMSG"
+targets=("poweroff" "rescue" "multi-user" "graphical" "reboot" "cancel")
+
+select pick in "${targets[@]}"
+do
+	case $pick in
+		poweroff)
+			sudo systemctl isolate poweroff.target
+			break
+			;;		
+		reboot)
+			sudo systemctl isolate reboot.target
+			break
+			;;		
+		rescue)
+			sudo systemctl isolate rescue.target
+			break
+			;;		
+		multi-user)
+			sudo systemctl isolate multi-user.target
+			break
+			;;		
+		graphical)
+			sudo systemctl isolate graphical.target
+			break
+			;;		
+		cancel)
+			break
+	esac
+done
+	
+	
+}
 
 function enable_services {
-	sudo rc-update add $(rc-status -s | awk '/stopped/ {print $1}' | fzf -m -e --reverse)
+	OUTPUTITEM=""
+	OUTPUTITEM=$(systemctl list-unit-files | awk '/disabled/ {print $1}' | fzf -m -e --reverse)
+	if [ "$OUTPUTITEM" != "" ]
+	then
+		sudo systemctl enable $OUTPUTITEM
+		STATUSVAR=$?
+	else
+		STATUSVAR=1
+	fi
 }
 
 function start_services {
-	sudo rc-service start $(rc-status -s | awk '/stopped/ {print $1}' | fzf -m -e --reverse)
+	OUTPUTITEM=""
+	OUTPUTITEM=$(systemctl list-unit-files | awk '/disabled/ {print $1}' | fzf -m -e --reverse)
+	if [ "$OUTPUTITEM" != "" ]
+	then
+		sudo systemctl start $OUTPUTITEM
+		STATUSVAR=$?
+	else
+		STATUSVAR=1
+	fi
 }
 
 function stop_services {
-	sudo rc-service stop $(rc-status -s | awk '/started/ {print $1}' | fzf -m -e --reverse)
+	OUTPUTITEM=""
+	OUTPUTITEM=$(systemctl list-unit-files | awk '/enabled/ {print $1}' | fzf -m -e --reverse)
+	if [ "$OUTPUTITEM" != "" ]
+	then
+		sudo systemctl stop $OUTPUTITEM
+		STATUSVAR=$?
+	else
+		STATUSVAR=1
+	fi
 }
 
 function disable_services {
-	sudo rc-update del $(rc-status -s | awk '/started/ {print $1}' | fzf -m -e --reverse)
+	OUTPUTITEM=""
+	OUTPUTITEM=$(systemctl list-unit-files | awk '/enabled/ {print $1}' | fzf -m -e --reverse)
+	if [ "$OUTPUTITEM" != "" ]
+	then
+		sudo systemctl disable $OUTPUTITEM
+		STATUSVAR=$?
+	else
+		STATUSVAR=1
+	fi
+
 }
 
     while true; do
@@ -58,7 +140,8 @@ function disable_services {
     echo -e " │    1   Enable services              2   Disable services    │"
     echo -e " │    3   Start services               4   Stop Services       │"
     echo -e " │    5   List active services         6   Show boot messages  │"    
-    echo -e " │    7   Edit configuration files                             │"
+    echo -e " │    7   Edit configuration files     8   Change runlevel     │"
+    echo -e " │    9   Analyze boot                                         │"
     echo -e " └─────────────────────────────────────────────────────────────┘"
     echo -e "          Select an item       -       0   Exit "
     echo ""
@@ -67,47 +150,94 @@ function disable_services {
         1)
             echo
             enable_services
-            echo ""
+	    if [ $STATUSVAR -eq 0 ]
+	    then
+		    echo "$SERVICEENABLEDMSG"
+		    echo "$CONTINMSG"
+		    read
+	    else
+		    echo ""
+	    fi
+	    STATUSVAR=0
             ;;
         2)
             echo
             disable_services
-            echo ""
+	    if [ $STATUSVAR -eq 0 ]
+	    then
+		    echo "$SERVICEDISABLEDMSG"
+		    echo "$CONTINMSG"
+		    read
+	    else
+		    echo ""
+	    fi
+	    STATUSVAR=0
             ;;
         3)
             echo
             start_services
-            echo ""
+	    if [ $STATUSVAR -eq 0 ]
+	    then
+		    echo "$SERVICESTARTEDMSG"
+		    echo "$CONTINMSG"
+		    read
+	    else
+		    echo""
+	    fi
+	    STATUSVAR=0
             ;;
         4)
             echo
             stop_services
-            echo ""
-            ;;
+	    if [ $STATUSVAR -eq 0 ]
+	    then
+		    echo "$SERVICESTOPPEDMSG"
+		    echo "$CONTINMSG"
+		    read
+	    else
+		    echo ""
+	    fi
+	    STATUSVAR=0
+	    ;;
         5)
             echo
-            rc-status
+            systemctl
             echo ""
+            echo "$CONTINMSG"
+            read
             ;;
         6)
             echo
+            journatlctl
             dmesg
             echo ""
+            echo "$CONTINMSG"
+            read
             ;;
         7)
             echo
             config_editor
             echo ""
             ;;
-        0)
-            clear && exit
+        8)
+            echo
+            change_runlevel
+            echo ""
+            ;;
+        9)
+            echo
+            systemd-analyze blame
+            echo ""
+            echo "$CONTINMSG"
             read
             ;;
+        0)
+            clear && exit
+            ;;
         *)
-            echo -e "$RED Wrong option $NC"
-            echo "Wait and try again later..."
-            echo ""
-            sleep 3
+            echo -e "$ERRORMSG"
+	    echo "$TRYAGAINMSG"
+            read
             clear
             ;;
     esac
